import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';

function read(path) {
  return readFileSync(path, 'utf8');
}

function assertPng(path) {
  assert.equal(existsSync(path), true, `${path} should exist`);
  assert.deepEqual([...readFileSync(path).subarray(0, 8)], [137, 80, 78, 71, 13, 10, 26, 10]);
}

test('home screen and PWA raster artwork is linked and cacheable', () => {
  const html = read('app/index.html');
  assert.match(html, /rel="apple-touch-icon" sizes="180x180" href="\/app\/icons\/family-tracker-icon-180\.png"/);
  assert.match(html, /class="home-hero-art" src="\/app\/icons\/family-tracker-icon-512\.png"/);

  const manifest = JSON.parse(read('app/manifest.webmanifest'));
  assert.deepEqual(manifest.icons.map((icon) => icon.src), [
    '/app/icons/family-tracker-icon-192.png',
    '/app/icons/family-tracker-icon-512.png',
  ]);
  assert.equal(manifest.icons[1].purpose, 'any maskable');

  const serviceWorker = read('app/sw.js');
  for (const asset of [
    '/app/icons/family-tracker-icon-180.png',
    '/app/icons/family-tracker-icon-192.png',
    '/app/icons/family-tracker-icon-512.png',
  ]) {
    assert.match(serviceWorker, new RegExp(asset.replace(/[/.]/g, '\\$&')));
  }

  assertPng('app/icons/family-tracker-source.png');
  assertPng('app/icons/family-tracker-icon-180.png');
  assertPng('app/icons/family-tracker-icon-192.png');
  assertPng('app/icons/family-tracker-icon-512.png');
});

test('PWA icons are generated by downsizing the single raster source', () => {
  const pkg = JSON.parse(read('package.json'));
  assert.equal(pkg.scripts['generate:pwa-icons'], 'node scripts/generate-pwa-icons.mjs');

  const generator = read('scripts/generate-pwa-icons.mjs');
  assert.match(generator, /family-tracker-source\.png/);
  assert.match(generator, /imageSmoothingQuality = 'high'/);
  assert.match(generator, /family-tracker-icon-180\.png/);
  assert.match(generator, /family-tracker-icon-192\.png/);
  assert.match(generator, /family-tracker-icon-512\.png/);
});
