import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';

function read(path) {
  return readFileSync(path, 'utf8');
}

function assertPng(path) {
  assert.equal(existsSync(path), true, `${path} should exist`);
  assert.deepEqual([...readFileSync(path).subarray(0, 8)], [137, 80, 78, 71, 13, 10, 26, 10]);
}

function readPngSize(path) {
  const buffer = readFileSync(path);
  assertPng(path);
  return {
    width: buffer.readUInt32BE(16),
    height: buffer.readUInt32BE(20),
  };
}

test('home screen and PWA raster artwork is linked and cacheable', () => {
  const html = read('app/index.html');
  assert.match(html, /rel="apple-touch-icon" sizes="180x180" href="\/app\/icons\/family-tracker-icon-180\.png"/);
  assert.match(html, /class="home-hero-art" src="\/app\/icons\/family-tracker-icon-512\.png"/);

  const manifest = JSON.parse(read('app/manifest.webmanifest'));
  assert.equal(manifest.scope, '/');
  assert.deepEqual(manifest.icons.map((icon) => icon.src), [
    '/app/icons/family-tracker-icon-192.png',
    '/app/icons/family-tracker-icon-512.png',
  ]);
  assert.equal(manifest.icons[1].purpose, 'any maskable');

  const serviceWorker = read('app/sw.js');
  assert.match(read('app/main.js'), /serviceWorker\.register\('\/sw\.js'\)/);
  assert.match(serviceWorker, /'\/sw\.js'/);
  assert.doesNotMatch(serviceWorker, /'\/app\/sw\.js'/);
  for (const asset of [
    '/app/icons/family-tracker-icon-180.png',
    '/app/icons/family-tracker-icon-192.png',
    '/app/icons/family-tracker-icon-512.png',
  ]) {
    assert.match(serviceWorker, new RegExp(asset.replace(/[/.]/g, '\\$&')));
  }

  assertPng('app/icons/family-tracker-source.png');
  assertPng('app/icons/family-tracker-icon-180.png');
  assertPng('app/icons/family-tracker-icon-192.png');
  assertPng('app/icons/family-tracker-icon-512.png');
});

test('PWA icons are generated by downsizing the single uploaded raster source', () => {
  const pkg = JSON.parse(read('package.json'));
  assert.equal(pkg.scripts['generate:pwa-icons'], 'node scripts/generate-pwa-icons.mjs');

  assert.equal(existsSync('app/icons/IMG_85084494-541D-4823-9CE0-DFB2326FA541.jpeg'), true);
  assert.deepEqual(readPngSize('app/icons/family-tracker-source.png'), { width: 1024, height: 1024 });
  assert.deepEqual(readPngSize('app/icons/family-tracker-icon-180.png'), { width: 180, height: 180 });
  assert.deepEqual(readPngSize('app/icons/family-tracker-icon-192.png'), { width: 192, height: 192 });
  assert.deepEqual(readPngSize('app/icons/family-tracker-icon-512.png'), { width: 512, height: 512 });

  const generator = read('scripts/generate-pwa-icons.mjs');
  assert.match(generator, /family-tracker-source\.png/);
  assert.match(generator, /imageSmoothingQuality = 'high'/);
  assert.match(generator, /family-tracker-icon-180\.png/);
  assert.match(generator, /family-tracker-icon-192\.png/);
  assert.match(generator, /family-tracker-icon-512\.png/);
});
